# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:

- script: |
    if not exist "vc_scripts" mkdir vc_scripts 
    xcopy /S /Q /Y "C:\Users\vaprti\vector\github\vectorcast-execution-plugin-tms-pipeline\src\main\resources\scripts\*.*" vc_scripts
    set path=%PATH%;C:\vector\tools\gnat\2019\bin
    set WORKSPACE=%CD%

    %VECTORCAST_DIR%/manage --project PluginTesting.vcm --build-execute --incremental --output RebuildReport.html > build.log
    %VECTORCAST_DIR%/manage --project PluginTesting.vcm --create-report=metrics --output=MetricsReport.html
    %VECTORCAST_DIR%/manage --project PluginTesting.vcm --full-status FullStatusReport.html

    %VECTORCAST_DIR%/vpython vc_scripts/generate-results.py PluginTesting.vcm --junit --buildlog build.log
    %VECTORCAST_DIR%/vpython vc_scripts/generate-results.py PluginTesting.vcm --final
  displayName: 'VectorCAST Build-Execute'
