-- VectorCAST 25.sp4 (08/19/25)
-- Test Case Script
--
-- Environment    : INTEGRATION_TESTING
-- Unit(s) Under Test: database encrypt linked_list manager matrix_multiply
--
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:REMOVED_CL_PREFIX
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STANDARD_SPACING_R2
TEST.SCRIPT_FEATURE:OVERLOADED_CONST_SUPPORT
TEST.SCRIPT_FEATURE:UNDERSCORE_NULLPTR
TEST.SCRIPT_FEATURE:FULL_PARAMETER_TYPES
TEST.SCRIPT_FEATURE:STRUCT_DTOR_ADDS_POINTER
TEST.SCRIPT_FEATURE:STRUCT_FIELD_CTOR_ADDS_POINTER
TEST.SCRIPT_FEATURE:STRUCT_BASE_CTOR_ADDS_POINTER
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Unit: manager

-- Subprogram: Place_Order

-- Test Case: Place_Order.Fuzz.Random
TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Place_Order.Fuzz.Random
TEST.VALUE_USER_CODE:manager.Place_Order.Table
<<manager.Place_Order.Table>> =  INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:manager.Place_Order.Seat
<<manager.Place_Order.Seat>> = INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:manager.Place_Order.Order.Soup
<<manager.Place_Order.Order>>.Soup = INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:manager.Place_Order.Order.Salad
<<manager.Place_Order.Order>>.Salad = INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:manager.Place_Order.Order.Entree
<<manager.Place_Order.Order>>.Entree = INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:manager.Place_Order.Order.Dessert
<<manager.Place_Order.Order>>.Dessert = INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:manager.Place_Order.Order.Beverage
<<manager.Place_Order.Order>>.Beverage = INT_MIN + rand() % (INT_MAX - INT_MAX + 1);
TEST.END_VALUE_USER_CODE:
TEST.END

-- COMPOUND TESTS

TEST.SUBPROGRAM:<<COMPOUND>>
TEST.NEW
TEST.NAME:FuzzTesting.001
TEST.END
--
