
set SQUORE_HOME=C:/Vector/tools/Squore
set SQUORE_PROJECT_NAME=PointOfSales_v2
set SQUORE_JAR=%SQUORE_HOME%/lib/squore-engine.jar
set SQUORE_URL=http://localhost:8180//SQuORE_Server
set SQUORE_COMMANDS=DELEGATE_CREATION
set VCAST_DEMO_SRC_BASE=%~dp0CurrentRelease
set path=%path%;c:/vector/tools/gnat/2017/bin

rem java -Dsquore.home.dir="%SQUORE_HOME%" -jar "%SQUORE_JAR%" --url="%SQUORE_URL%" --commands="%SQUORE_COMMANDS%" --name="PointOfSales_v2" --color="rgb(192,255,255)" --autoBaseline="true" --login="demo" --wizardId="ANALYTICS" --dp="type=SQuORE,languages=c:.c,.C;cpp:.cpp,.CPP,.h,.H,pattern_dir=vcast-workarea;PluginTesting;" --dp="type=VectorCAST_API,project_file_list=C:/Users/vaprti/vector/github/PointOfSales_v2/CurrentRelease/vcast-workarea/vc_manage/PointOfSales_Manage.vcm" --dp="type=qac,txt=C:/Users/vaprti/vector/github/PointOfSales_v2/qac/qac_report.tab" --repository="path=C:/Users/vaprti/vector/github/PointOfSales_v2"

java -Dsquore.home.dir="%SQUORE_HOME%" -jar "%SQUORE_JAR%" --url="%SQUORE_URL%" --commands="%SQUORE_COMMANDS%" --name="PointOfSales_v2" --color="rgb(192,255,255)" --autoBaseline="true" --login="demo" --wizardId="ANALYTICS" --dp="type=SQuORE,languages=c:.c,.C;cpp:.cpp,.CPP,.h,.H,pattern_dir=vcast-workarea;PluginTesting;" --dp="type=VectorCAST_API,project_file_list=C:/Users/vaprti/vector/github/PointOfSales_v2/CurrentRelease/vcast-workarea/vc_manage/PointOfSales_Manage.vcm" --dp="type=import_ticket,input_file=C:\Users\vaprti\vector\github\PointOfSales_v2\squore\PointOfSalesTickets.csv,artefact_id=ID,artefact_name=${ID}: ${Summary},artefact_uid=TK#${ID},artefact_groups=Category,definition_open=Status=[Open|Reopened|Waiting Info|Spec Validation|Help Me|Estimated],definition_rd_progress=Status=[Analysing|Being Analyzed|Implementing],definition_vv_progress=Status=[Documenting|Verifying],definition_close=Status=[Closed|Rejected|Postponed],definition_defect=Type=[Problem|Question],definition_enhancement=Type=[Evolution|User Story|Task],in_todo_list=Sprint=[1|2|3|4|5],creation_date=Date Submitted,last_updated_date=Updated,closure_date=Updated;Status=[Closed|Verifying|Rejected|Documenting|Postponed],url=https://github.com/squoregit/earthRepo/issues/${ID},description=Summary,reporter=Reporter,handler=Assigned To,priority=Priority,severity=Severity,csv_separator=,,informations=Sprint;Project;Category;Time Estimate;Status;Type;Target Version;Fixed in Version;Summary;Priority;Severity;Reporter;Assigned To;ID;Workload;Company,createOutput=false" --dp="type=qac,txt=C:/Users/vaprti/vector/github/PointOfSales_v2/qac/qac_report.tab" --repository="path=C:/Users/vaprti/vector/github/PointOfSales_v2"
