
set SQUORE_HOME=C:/Vector/tools/Squore
set SQUORE_PROJECT_NAME=PointOfSales_v2
set SQUORE_JAR=%SQUORE_HOME%/lib/squore-engine.jar
set SQUORE_URL=http://localhost:8180//SQuORE_Server
set SQUORE_COMMANDS=DELEGATE_CREATION
set VCAST_DEMO_SRC_BASE=%~dp0CurrentRelease
set path=%path%;c:/vector/tools/gnat/2017/bin

java -Dsquore.home.dir="%SQUORE_HOME%" -jar "%SQUORE_JAR%" --url="%SQUORE_URL%" --commands="%SQUORE_COMMANDS%" --name="PointOfSales_v2" --color="rgb(192,255,255)" --autoBaseline="true" --login="demo" --wizardId="ANALYTICS" --dp="type=SQuORE,languages=c:.c,.C;cpp:.cpp,.CPP,.h,.H,pattern_dir=vcast-workarea;PluginTesting;" --dp="type=VectorCAST_API,project_file_list=C:/Users/vaprti/vector/github/PointOfSales_v2/CurrentRelease/vcast-workarea/vc_manage/PointOfSales_Manage.vcm,create_path_unique_id=true" --dp="type=import_excel,input_file=C:\Users\vaprti\vector\github\PointOfSales_v2\squore\PointOfSalesRequirements.xlsx,sheetname=PointOfSalesRequirements,artefact_type=REQ,artefact_type_container=REQ_FOLDER,artefact_uid=${ID},artefact_link=TESTED?column=Tests&direction=IN&separator=';',artefact_name=${ID}:${Title},path_list=Requirement;Category,info_list=ID?column=ID;DESCRIPTION?column=Description;NAME?column=Title;STATUS?column=Test Result,metric_list=REQ_STATUS?column=Status&map=[In Progress:0,Draft:1,Reviewed:2,Released:3,Verified:4,Postponed:5];CRITICAL_FACTOR?column=Criticity&map=[QM:0,A:1,B:2,C:3,D:4],date_list=CREATION_DATE?column=Created;LAST_UPDATE?column=Modified" --dp="type=import_ticket,input_file=C:\Users\vaprti\vector\github\PointOfSales_v2\squore\PointOfSalesTickets.csv,artefact_id=ID,artefact_name=${ID}: ${Summary},artefact_uid=TK#${ID},artefact_groups=Category,definition_open=Status=[Open|Reopened|Waiting Info|Spec Validation|Help Me|Estimated],definition_rd_progress=Status=[Analysing|Being Analyzed|Implementing],definition_vv_progress=Status=[Documenting|Verifying],definition_close=Status=[Closed|Rejected|Postponed],definition_defect=Type=[Problem|Question],definition_enhancement=Type=[Evolution|User Story|Task],in_todo_list=Sprint=[1|2|3|4|5],creation_date=Date Submitted,last_updated_date=Updated,closure_date=Updated;Status=[Closed|Verifying|Rejected|Documenting|Postponed],url=https://github.com/squoregit/earthRepo/issues/${ID},description=Summary,reporter=Reporter,handler=Assigned To,priority=Priority,severity=Severity,csv_separator=,,informations=Sprint;Project;Category;Time Estimate;Status;Type;Target Version;Fixed in Version;Summary;Priority;Severity;Reporter;Assigned To;ID;Workload;Company,createOutput=false" --dp="type=project_date,excel_file=C:\Users\vaprti\vector\github\PointOfSales_v2\squore\Timing Plan.xlsx,excel_sheet=Task_Table,task_name=Software Development (21.21.142.1)" --dp="type=qac,txt=C:/Users/vaprti/vector/github/PointOfSales_v2/qac/qac_report.tab" --repository="path=C:/Users/vaprti/vector/github/PointOfSales_v2"



