name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make_gcov
      run: cd fast_test/tutorial/c & make test GCOV=1
    - name: make coco
      run: cd fast_test/tutorial/c & make coco
