name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: pip install gcovr
      run: pip install gcovr
    - name: make_gcov
      run: cd fast_test/tutorial/c;make test GCOV=1
    - name: make coco
      run: export CI_PROJECT_DIR=`pwd`;cd fast_test/tutorial/c;make coco
      
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: 5monkeys/cobertura-action@master
        with:
          path: fast_test/tutorial/c/coverage.xml
          minimum_coverage: 75
