name: GitHub Action for VectorCAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  # Relative path from checkout to the VectorCAST Project
  VC_Project: "fast_test.vcm"

  # Use --ci for VectorCAST Continuous Integration (headless) licenses; otherwise, set to ""
  VC_UseCILicense: "--ci"

  # Use "--incremental" to use VecteorCAST Change Based Testing; otherwise, set to ""
  VC_useCBT: "--incremental"
  
  # Use "--jobs=##" to use parallel number of jobs per compiler node; otherwise, for serial build/execute set to "" or "--jobs=1"
  VC_jobs: "--jobs=4"
  
jobs:
  build:

    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./fast_test
        
    steps:
    - uses: actions/checkout@v3
    
    # run the VC Project
    - name: VectorCAST Build/Execute
      run: Start-Process -NoNewWindow -wait $env:VECTORCAST_DIR\vpython.exe  -ArgumentList ".\vc_scripts\vcast_exec.py `"$VC_Project`" --build-execute --junit --cobertura --aggregate $VC_UseCILicense $VC_useCBT $VC_jobs"

       
    # Cobertura reporting
    - name: Publish Cobertura Report
      uses: 5monkeys/cobertura-action@master
      with:
          path: '**/xml_data/cobertura/coverage_results*.xml'
          minimum_coverage: 0  
          
    # Junit reporting
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/xml_data/junit/test_results*.xml'
        detailed_summary: true
        fail_on_failure: true
        include_passed: true
        
      
