name: GitHub Action for VectorCAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
    contents: read
    checks: write
    id-token: write
    
env:
  # Relative path from checkout to the VectorCAST Project
  VC_Project: "fast_test.vcm"

  # Use --ci for VectorCAST Continuous Integration (headless) licenses; otherwise, set to ""
  VC_UseCILicense: "--ci"

  # Use "--incremental" to use VecteorCAST Change Based Testing; otherwise, set to ""
  VC_useCBT: "--incremental"
  
  # Use "--jobs=##" to use parallel number of jobs per compiler node; otherwise, for serial build/execute set to "" or "--jobs=1"
  VC_jobs: "--jobs=4"

  # sets the extra self-signed cert
  NODE_EXTRA_CA_CERTS: "d:\\vector\\certs\\Vector_Root_CA_2.0.crt"
  
jobs:
  VectorCAST:

    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./fast_test
        
    steps:
    - uses: actions/checkout@v3
    
    # run the VC Project
    - name: VectorCAST Build/Execute
      run: Start-Process -NoNewWindow -wait $env:VECTORCAST_DIR\vpython.exe  -ArgumentList ".\vc_scripts\vcast_exec.py fast_test.vcm --build-execute --junit --cobertura --aggregate $VC_UseCILicense --incremental --jobs 4"
       
    # Cobertura reporting
    - name: Publish Cobertura Report
      uses: 5monkeys/cobertura-action@master
      with:
          path: '**/xml_data/cobertura/coverage_results*.xml'
          minimum_coverage: 0  
          show_line: true
          show_branch: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
    # Junit reporting
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
      
        report_paths: '**/xml_data/junit/test_results*.xml'
        detailed_summary: true
        fail_on_failure: false
        include_passed: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        summary: true
        check_name: VectorCAST Test Results
        annotate_only: true
        
    # Save metrics artifacts
    - name: Metrics XML Files
      uses: actions/upload-artifact@v3
      with:
        name: Metrics XML Files
        path: "**/xml_data"

    # Save HTML Reports
    - name: HTML Reports
      uses: actions/upload-artifact@v3
      with:
        name: HTML Reports
        path: "**/fast_test*.html"
        
